#############################################################################
# Makefile for building: BlankNGL
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  BlankNGL.pro
# Template: app
# Command: /home/elmatto/Qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile BlankNGL.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/home/elmatto/NGL/include -I/home/elmatto/Qt/5.5/gcc_64/include -I/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL -I/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets -I/home/elmatto/Qt/5.5/gcc_64/include/QtGui -I/home/elmatto/Qt/5.5/gcc_64/include/QtCore -Imoc -I/home/elmatto/Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/elmatto/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BlankNGL1.0.0
DISTDIR = /home/elmatto/programming/Specialist/obj/BlankNGL1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/elmatto/Qt/5.5/gcc_64 -Wl,-rpath,/home/elmatto/NGL/lib -Wl,-rpath,/home/elmatto/Qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -L/home/elmatto/NGL/lib -l NGL -L/home/elmatto/Qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/NGLScene.cpp \
		src/SwarmFactory.cpp \
		src/Member.cpp \
		src/Bird.cpp \
		src/Camera.cpp \
		src/FollowPoint.cpp \
		src/AvoidShapes.cpp 
OBJECTS       = obj/main.o \
		obj/NGLScene.o \
		obj/SwarmFactory.o \
		obj/Member.o \
		obj/Bird.o \
		obj/Camera.o \
		obj/FollowPoint.o \
		obj/AvoidShapes.o
DIST          = BlankNGL.pro include/NGLScene.h \
		include/SwarmFactory.h \
		include/Member.h \
		include/Bird.h \
		include/Camera.h \
		include/FollowPoint.h \
		include/AvoidShapes.h src/main.cpp \
		src/NGLScene.cpp \
		src/SwarmFactory.cpp \
		src/Member.cpp \
		src/Bird.cpp \
		src/Camera.cpp \
		src/FollowPoint.cpp \
		src/AvoidShapes.cpp
QMAKE_TARGET  = BlankNGL
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = BlankNGL


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BlankNGL.pro .qmake.cache /home/elmatto/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /home/elmatto/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/elmatto/NGL/UseNGL.pri \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/c++11.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qml_debug.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		BlankNGL.pro \
		/home/elmatto/Qt/5.5/gcc_64/lib/libQt5OpenGL.prl \
		/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile BlankNGL.pro
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/unix.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/linux.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/qconfig.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
/home/elmatto/NGL/UseNGL.pri:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/c++11.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qml_debug.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/qt.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/resources.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/moc.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/uic.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
/home/elmatto/Qt/5.5/gcc_64/mkspecs/features/lex.prf:
BlankNGL.pro:
/home/elmatto/Qt/5.5/gcc_64/lib/libQt5OpenGL.prl:
/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Gui.prl:
/home/elmatto/Qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile BlankNGL.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/SwarmFactory.h include/Member.h include/Bird.h include/Camera.h include/FollowPoint.h include/AvoidShapes.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/NGLScene.cpp src/SwarmFactory.cpp src/Member.cpp src/Bird.cpp src/Camera.cpp src/FollowPoint.cpp src/AvoidShapes.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/main.o: src/main.cpp /home/elmatto/Qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		include/NGLScene.h \
		include/Camera.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h \
		include/SwarmFactory.h \
		include/Bird.h \
		include/Member.h \
		include/FollowPoint.h \
		/home/elmatto/NGL/include/ngl/VAOPrimitives.h \
		/home/elmatto/NGL/include/ngl/Singleton.h \
		/home/elmatto/NGL/include/ngl/Camera.h \
		/home/elmatto/NGL/include/ngl/Mat4.h \
		/home/elmatto/NGL/include/ngl/Plane.h \
		/home/elmatto/NGL/include/ngl/AABB.h \
		/home/elmatto/NGL/include/ngl/Light.h \
		/home/elmatto/NGL/include/ngl/Transformation.h \
		/home/elmatto/NGL/include/ngl/Text.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QHash \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QFont \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QObject \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QEvent \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QMargins \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QRect \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qicon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QImage \
		/home/elmatto/NGL/include/ngl/ShaderLib.h \
		/home/elmatto/NGL/include/ngl/Shader.h \
		/home/elmatto/NGL/include/ngl/ShaderProgram.h \
		/home/elmatto/NGL/include/ngl/Util.h \
		/home/elmatto/NGL/include/ngl/Mat3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/NGLScene.o: src/NGLScene.cpp /home/elmatto/Qt/5.5/gcc_64/include/QtGui/QMouseEvent \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QGuiApplication \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		include/NGLScene.h \
		include/Camera.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h \
		include/SwarmFactory.h \
		include/Bird.h \
		include/Member.h \
		include/FollowPoint.h \
		/home/elmatto/NGL/include/ngl/VAOPrimitives.h \
		/home/elmatto/NGL/include/ngl/Singleton.h \
		/home/elmatto/NGL/include/ngl/Camera.h \
		/home/elmatto/NGL/include/ngl/Mat4.h \
		/home/elmatto/NGL/include/ngl/Plane.h \
		/home/elmatto/NGL/include/ngl/AABB.h \
		/home/elmatto/NGL/include/ngl/Light.h \
		/home/elmatto/NGL/include/ngl/Transformation.h \
		/home/elmatto/NGL/include/ngl/Text.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QHash \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QFont \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QPaintDeviceWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QWindow \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindow.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QObject \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QEvent \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QMargins \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QRect \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurface.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qicon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QPaintDevice \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/QScopedPointer \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QImage \
		/home/elmatto/NGL/include/ngl/ShaderLib.h \
		/home/elmatto/NGL/include/ngl/Shader.h \
		/home/elmatto/NGL/include/ngl/ShaderProgram.h \
		/home/elmatto/NGL/include/ngl/Util.h \
		/home/elmatto/NGL/include/ngl/Mat3.h \
		/home/elmatto/NGL/include/ngl/NGLInit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/SwarmFactory.o: src/SwarmFactory.cpp include/SwarmFactory.h \
		include/Bird.h \
		include/Member.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SwarmFactory.o src/SwarmFactory.cpp

obj/Member.o: src/Member.cpp include/Member.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Member.o src/Member.cpp

obj/Bird.o: src/Bird.cpp include/Bird.h \
		include/Member.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h \
		include/SwarmFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bird.o src/Bird.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/FollowPoint.o: src/FollowPoint.cpp include/FollowPoint.h \
		include/Member.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h \
		/home/elmatto/NGL/include/ngl/VAOPrimitives.h \
		/home/elmatto/NGL/include/ngl/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FollowPoint.o src/FollowPoint.cpp

obj/AvoidShapes.o: src/AvoidShapes.cpp include/AvoidShapes.h \
		include/Member.h \
		/home/elmatto/NGL/include/ngl/Obj.h \
		/home/elmatto/NGL/include/ngl/Types.h \
		/home/elmatto/NGL/include/ngl/glew.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/QGLContext \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qgl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qflags.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qt_windows.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopengles2ext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qopenglext.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstring.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qchar.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qrect.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsize.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qpair.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvector.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qregion.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qline.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qimage.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qhash.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfont.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qevent.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qmap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qset.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurl.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfile.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpaintengine.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpainter.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qpen.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/QSurfaceFormat \
		/home/elmatto/Qt/5.5/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/elmatto/NGL/include/ngl/Texture.h \
		/home/elmatto/NGL/include/ngl/Image.h \
		/home/elmatto/NGL/include/ngl/Colour.h \
		/home/elmatto/NGL/include/ngl/Vec4.h \
		/home/elmatto/NGL/include/ngl/Vec2.h \
		/home/elmatto/NGL/include/ngl/Vec3.h \
		/home/elmatto/NGL/include/ngl/AbstractMesh.h \
		/home/elmatto/NGL/include/ngl/BBox.h \
		/home/elmatto/NGL/include/ngl/VertexArrayObject.h \
		/home/elmatto/NGL/include/ngl/RibExport.h \
		/home/elmatto/NGL/include/ngl/NGLassert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/AvoidShapes.o src/AvoidShapes.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

